import type { City, Nation, Province, Resource, Terrain, World } from "./types";
import type { EventLang } from "./eventText";
import { staticZh, phraseZh } from "./localizationZh";

export type Language = "en" | "zh" | "es";

type NamedEntity = Pick<Nation | City | Province, "name" | "nameEn" | "nameZh" | "nameEs">;

export function getLocalizedName(entity: NamedEntity | undefined, language: Language) {
  if (!entity) return "";
  if (language === "zh") return entity.nameZh ?? "";
  if (language === "es") return entity.nameEs ?? entity.nameEn ?? entity.name ?? "";
  return entity.nameEn ?? entity.name ?? "";
}

const staticEs: Record<string, string> = {
  "AI Civilization Sandbox": "AI Civilization Sandbox",
  "World Observer": "Observador Mundial",
  "World Time": "Tiempo del Mundo",
  "World map": "Mapa del Mundo",
  "World controls": "Controles del Mundo",
  "Map mode": "Modo de Mapa",
  "Event log": "Bitácora de Eventos",
  "Event log mode": "Modo de Bitácora",
  "Simulation speed": "Velocidad de Simulación",
  "Collapse event log": "Contraer bitácora",
  "Expand event log": "Expandir bitácora",
  "Collapse side panel": "Contraer panel lateral",
  "Expand side panel": "Expandir panel lateral",
  Play: "Jugar",
  Pause: "Pausar",
  "Next Turn": "Siguiente Turno",
  "Turn Progress": "Progreso del Turno",
  Resolving: "Resolviendo",
  Seed: "Semilla",
  Map: "Mapa",
  Provinces: "Provincias",
  Nations: "Naciones",
  Cities: "Ciudades",
  Towns: "Pueblos",
  Tiles: "Tiles",
  Political: "Política",
  Terrain: "Terreno",
  Resources: "Recursos",
  Layers: "Capas",
  "Province border": "Borde de provincia",
  "Nation border": "Borde de nación",
  "Nation color edge": "Borde de color de nación",
  "Resource node": "Nodo de recurso",
  City: "Ciudad",
  "Selected Province": "Provincia Seleccionada",
  "View Nation": "Ver Nación",
  Area: "Área",
  Elevation: "Elevación",
  Temperature: "Temperatura",
  Moisture: "Humedad",
  "None discovered": "Sin descubrir",
  Details: "Detalles",
  "Click a nation to open its detail panel.": "Haz clic en una nación para abrir su panel de detalles.",
  "World History": "Historia del Mundo",
  "Event Log": "Bitácora de Eventos",
  Overview: "General",
  General: "General",
  Nation: "Nación",
  "Nación": "Nación",
  Guerra: "Guerra",
  Mercado: "Mercado",
  Diplomacia: "Diplomacia",
  Expansiones: "Expansiones",
  Espionaje: "Espionaje",
  Todos: "Todos",
  Combate: "Combate",
  "Logística": "Logística",
  Ofertas: "Ofertas",
  Transacciones: "Transacciones",
  "Market Summary": "Resumen de Mercado",
  "Free Territory": "Territorio libre",
  "Tierra libre": "Tierra libre",
  "Recent Major Events": "Eventos Mayores Recientes",
  Back: "Atrás",
  "Last 2 Years": "Últimos 2 Años",
  "No major events yet": "Sin eventos mayores aún",
  "Capital City": "Capital",
  "City Detail": "Detalle de Ciudad",
  Population: "Población",
  "Monthly Gold": "Oro Mensual",
  Army: "Ejército",
  Defense: "Defensa",
  "Building Slots": "Ranuras de Edificios",
  Empty: "Vacío",
  "Nation Detail": "Detalle de Nación",
  Capital: "Capital",
  Era: "Era",
  Stone: "Piedra",
  Ancient: "Antigua",
  Medieval: "Medieval",
  "Dark Medieval": "Oscura",
  Modern: "Moderna",
  Contemporary: "Contemporánea",
  Treasury: "Tesoro",
  Soldiers: "Soldados",
  Morale: "Moral",
  "Resource Sites": "Yacimientos",
  "Deployed Spies": "Espías Desplegados",
  "AI Policy": "Política de IA",
  Expansion: "Expansión",
  Economy: "Economía",
  Diplomacy: "Diplomacia",
  "Spy Missions": "Misiones de Espionaje",
  Military: "Militar",
  "Spy Network": "Red de Espionaje",
  "Diplomacy Status": "Estado Diplomático",
  "Major Cities": "Ciudades Principales",
  Relations: "Relaciones",
  "Monthly Output": "Producción Mensual",
  "Current Resources": "Recursos Actuales",
  "Monthly Upkeep": "Mantenimiento Mensual",
  "Attack / Defense": "Ataque / Defensa",
  "Field Army Groups": "Grupos de Ejército de Campo",
  "City Garrisons": "Guarniciones de Ciudad",
  "Recruitment Queue": "Cola de Reclutamiento",
  "Active Wars": "Guerras Activas",
  "No field army groups deployed": "Sin grupos de ejército de campo desplegados",
  "No city garrisons": "Sin guarniciones de ciudad",
  "No active recruitment orders": "Sin órdenes de reclutamiento activas",
  "No active wars": "Sin guerras activas",
  "No policy assessment available": "Sin evaluación de política disponible",
  "No spies currently deployed": "Sin espías desplegados actualmente",
  "Active Intelligence": "Inteligencia Activa",
  "No active intelligence reports": "Sin informes de inteligencia activos",
  "No active spy mission intent": "Sin intención de misión de espionaje activa",
  "No cities founded": "Sin ciudades fundadas",
  "No known relations": "Sin relaciones conocidas",
  "No resources discovered": "Sin recursos descubiertos",
  "No resources": "Sin recursos",
  "No target": "Sin objetivo",
  "Unknown nation": "Nación desconocida",
  "Unknown province": "Provincia desconocida",
  Unknown: "Desconocido",
  War: "Guerra",
  Alliance: "Alianza",
  "Vassal Of": "Séquito de",
  Vassal: "Séquito",
  Truce: "Tregua",
  "Mutual defense": "Defensa Mutua",
  "Limited treaty": "Tratado Limitado",
  Sent: "Enviado",
  Received: "Recibido",
  Active: "Activo",
  "Current report": "Informe actual",
  Attack: "Atacar",
  Defend: "Defender",
  Garrison: "Guarnición",
  Raid: "Incursión",
  Rally: "Reunión",
  Retreat: "Retirada",
  "No wars, treaties, vassals, truces, or proposals": "Sin guerras, tratados, séquitos, treguas o propuestas",
  "Drag to pan / Wheel to zoom": "Arrastra para panorámica / Rueda para zoom",
  Grain: "Cereal",
  Timber: "Madera",
  Iron: "Hierro",
  Coal: "Carbón",
  Oil: "Petróleo",
  Plain: "Llano",
  Forest: "Bosque",
  Hill: "Colina",
  Mountain: "Montaña",
  Desert: "Desierto",
  Coast: "Costa",
  Ocean: "Océano",
  grain: "cereal",
  timber: "madera",
  iron: "hierro",
  coal: "carbón",
  oil: "petróleo",
  plain: "llano",
  forest: "bosque",
  hill: "colina",
  mountain: "montaña",
  desert: "desierto",
  coast: "costa",
  ocean: "océano",
  tiles: "casillas",
  slots: "ranuras",
  soldiers: "soldados",
  steps: "pasos",
  battles: "batallas",
  months: "meses",
  sites: "yacimientos",
  Hostile: "Hostil",
  Wary: "Receloso",
  Neutral: "Neutral",
  Friendly: "Amistoso",
  Trusted: "Confiable",
  "Declare War": "Declarar Guerra",
  "Seek Alliance": "Buscar Alianza",
  "Demand Vassalage": "Exigir Sumisión",
  "Seek Vassalage": "Buscar Séquito",
  "Control Resources": "Controlar Recursos",
  "Control Cities": "Controlar Ciudades",
  "Decisive Battle": "Batalla Decisiva",
  Recovery: "Recuperación",
  Construction: "Construcción",
  "Army Building": "Reclutar Ejército",
  "Gather Intelligence": "Recolectar Inteligencia",
  "Improve Relations": "Mejorar Relaciones",
  "Damage Relations": "Dañar Relaciones",
  "Sow Discord": "Sembrar Discórdia",
  None: "Ninguno",
  "gather intelligence": "recolectar inteligencia",
  "improve relations": "mejorar relaciones",
  "damage relations": "dañar relaciones",
  "sow discord": "sembrar discórdia",
  "No Expansion": "Sin Expansión",
  "No Diplomatic Move": "Sin Acción Diplomática",
  "Seek Peace": "Buscar Paz",
  Surrender: "Rindirse",
  Militia: "Milicia",
  Infantry: "Infantería",
  "Light Cavalry": "Caballería Ligera",
  "Heavy Cavalry": "Caballería Pesada",
  Cavalry: "Caballería",
  Levy: "Leva",
  militia: "milicia",
  infantry: "infantería",
  "light cavalry": "caballería ligera",
  "heavy cavalry": "caballería pesada",
  cavalry: "caballería",
  levy: "leva",
  attack: "ataque",
  defend: "defensa",
  garrison: "guarnición",
  raid: "incursión",
  rally: "reunión",
  retreat: "retirada",
  "Spy Dispatched": "Espía Desplegado",
  "Intelligence Acquired": "Inteligencia Adquirida",
  "Relations Sowed Discord": "Relaciones: Discórdia Sembrada",
  "Relations Improved": "Relaciones Mejoradas",
  "Relations Damaged": "Relaciones Dañadas",
  "War Declared": "Guerra Declarada",
  "War Continued": "Guerra Continúa",
  "Levy Called": "Leva Llamada",
  "Alliance Signed": "Alianza Firmada",
  "Truce Signed": "Tregua Firmada",
  "Vassalage Accepted": "Sumisión Aceptada",
  "Alliance Dissolved": "Alianza Disuelta",
  "Vassalage Broken": "Sumisión Rupturada",
  "Vassal Rebellion": "Rebelión de Séquito",
  "Military Upkeep Shortage": "Escasez de Fondos Militares",
  "Military Supply Shortage": "Escasez de Suministros Militares",
  "War Ended": "Guerra Terminada",
  "Nation Defeated": "Nación Derrotada",
  "Military Disbanded": "Ejército Disuelto",
  "Recruitment Completed": "Reclutamiento Completado",
  "City Developed": "Ciudad Desarrollada",
  "Army Group Created": "Grupo de Ejército Creado",
  "Army Group Ordered": "Grupo de Ejército Ordenado",
  "Army Group Moved": "Grupo de Ejército Movido",
  "Army Groups Merged": "Grupos de Ejército Fusionados",
  "Battle Won": "Batalla Ganada",
  "Battle Held": "Batalla Mantenida",
  "Province Occupied": "Provincia Ocupada",
  "Capital Lost": "Capital Perdida",
  "City Lost": "Ciudad Perdida",
  "Defeated Nation": "Nación Derrotada",
  "Defeated At": "Derrotada en",
  "Destroyed By": "Destruida por",
  "Alliance Request": "Solicitud de Alianza",
  "Peace Offer": "Oferta de Paz",
  "Vassalage Demand": "Exigencia de Sumisión",
  "Vassalage Offer": "Oferta de Séquito",
  "AI Configuration": "Configuración de IA",
  "Models & personalities": "Modelos y Personalidades",
  "Nation AI Configuration": "Configuración de IA de Nación",
  "Back to World": "Volver al Mundo",
  "Configure an OpenAI-compatible model and a distinct national personality for every nation.": "Configura un modelo compatible con OpenAI y una personalidad nacional distinta para cada nación.",
  "Unsaved changes": "Cambios no guardados",
  "Selected Nation": "Nación Seleccionada",
  "Enable External Model": "Habilitar Modelo Externo",
  "External model enabled": "Modelo externo habilitado",
  "Simulation AI": "IA de Simulación",
  "Browser-only configuration": "Solo guardado en el navegador",
  "API Keys are stored in this browser. Do not enter production credentials on a shared device.": "Las claves API se almacenan en este navegador. No ingreses credenciales de producción en un dispositivo compartido.",
  "Provider Name": "Nombre del Proveedor",
  "API Endpoint": "Endpoint de API",
  "Model Name": "Nombre del Modelo",
  "API Key": "Clave API",
  "Example: OpenRouter, DeepSeek, Ollama": "Ejemplo: OpenRouter, DeepSeek, Ollama",
  "Enter the complete OpenAI-compatible Chat Completions endpoint.": "Introduce el endpoint completo de Chat Completions compatible con OpenAI.",
  "Example: provider/model-name": "Ejemplo: proveedor/nombre-modelo",
  "Optional for local services": "Opcional para servicios locales",
  Show: "Mostrar",
  Hide: "Ocultar",
  "Nation Personality Prompt": "Prompt de Personalidad de Nación",
  "Describe this nation's values, ambitions, temperament, and strategic style.": "Describe los valores, ambiciones, temperamento y estilo estratégico de esta nación.",
  "This prompt is sent as the system message before the game's structured decision request.": "Este prompt se envía como mensaje del sistema antes de la solicitud de decisión estructurada del juego.",
  "Restore Nation Defaults": "Restaurar Valores Predeterminados",
  "Test Connection": "Probar Conexión",
  "Testing...": "Probando…",
  "Testing connection...": "Probando conexión…",
  "Save Configuration": "Guardar Configuración",
  "Connection successful.": "Conexión exitosa.",
  "Configuration saved locally.": "Configuración guardada localmente.",
  "Unable to save configuration in this browser.": "No se puede guardar la configuración en este navegador.",
  "Enter a valid HTTP or HTTPS API endpoint.": "Introduce un endpoint de API HTTP o HTTPS válido.",
  "Enter a model name before testing the connection.": "Introduce un nombre de modelo antes de probar la conexión.",
  "The model service rejected the request. Check the model name and API Key.": "El servicio de modelo rechazó la solicitud. Comprueba el nombre del modelo y la clave API.",
  "Connection timed out. Check the API endpoint and network.": "La conexión expiró. Comprueba el endpoint de API y la red.",
  "Unable to reach the model service. Check the endpoint, network, and CORS settings.": "No se puede alcanzar el servicio de modelo. Comprueba el endpoint, la red y la configuración CORS.",
  "Connection test failed unexpectedly.": "La prueba de conexión falló inesperadamente.",
  "No Nations Available": "Sin Naciones Disponibles",
  "Main Menu": "Menú Principal",
  "Main Menu Actions": "Acciones del Menú Principal",
  "Start Game": "Iniciar Juego",
  "Game Language": "Idioma del Juego",
  "A World Shaped by Autonomous Nations": "Un Mundo Moldeado por Naciones Autónomas",
  "Civilization Sandbox": "Sandbox de Civilización",
  "Generate a living world, then watch ambitious nations expand, negotiate, build, spy, and wage war one turn at a time.": "Genera un mundo vivo y observa cómo naciones ambiciosas se expanden, negocian, construyen, espían y hacen la guerra turno a turno.",
  "New World": "Nuevo Mundo",
  "Create a Civilization": "Crear Civilización",
  "World Seed": "Semilla del Mundo",
  "Enter any word or number": "Introduce cualquier palabra o número",
  "The same settings and seed will generate the same starting world.": "La misma configuración y semilla generarán el mismo mundo inicial.",
  "Nation Count": "Cantidad de Naciones",
  "City Count": "Cantidad de Ciudades",
  "Town Count": "Cantidad de Pueblos",
  "World Preview": "Vista Previa del Mundo",
  "Generate World": "Generar Mundo",
  "2–12 nations": "2–12 naciones",
};

const phraseEs: Array<[RegExp, string]> = [
  [/Year (\d+), Month (\d+)/g, "Año $1, Mes $2"], [/Turn (\d+)/g, "Turno $1"],
  [/(\d+) nations · (\d+) cities/g, "$1 naciones · $2 ciudades"],   [/(\d+) nations · (\d+) towns/g, "$1 naciones · $2 pueblos"], [/(\d+)–(\d+) towns/g, "$1–$2 pueblos"], [/(\d+)–(\d+) cities/g, "$1–$2 ciudades"],
  [/(\d+) of (\d+) nations completed/g, "$1 de $2 naciones completadas"], [/Waiting for /g, "Esperando"],
  [/Next in (\d+) months/g, "Próximo en $1 meses"], [/(\d+) months/g, "$1 meses"], [/(\d+) mo\b/g, "$1 mes"],
  [/(\d+) soldiers/g, "$1 soldados"], [/(\d+) battles/g, "$1 batallas"], [/(\d+) steps/g, "$1 pasos"],
  [/(\d+) slots/g, "$1 ranuras"], [/(\d+) sites/g, "$1 yacimientos"], [/(\d+) active/g, "$1 activo"],
  [/(\d+) tiles/g, "$1 casillas"],
  [/(\d+) deployed/g, "$1 desplegados"], [/(\d+) assigned/g, "$1 asignados"],
  [/\/month/g, "/mes"], [/\/mo\b/g, "/mes"], [/Ready /g, "Listo"], [/Started /g, "Iniciado"], [/Expires /g, "Expira"],
  [/Review /g, "Revisar"], [/Score /g, "Puntuación"], [/front /g, "frente"], [/gold/g, "oro"], [/resources/g, "recursos"],
  [/Attitude /g, "Actitud "], [/Level /g, "Nivel "], [/Active in /g, "Activo en"], [/ tribute/g, " tributo"],
  [/No immediate tense border target or insufficient army density\./g, "Sin objetivo de frontera tenso o densidad de ejército insuficiente."],
  [/Reserves are thin, so the economy is conserving gold and resources\./g, "Las reservas son bajas, así que la economía ahorra oro y recursos."],
  [/The army is dense enough to seek a direct confrontation\./g, "El ejército es lo suficientemente denso para buscar un enfrentamiento directo."],
  [/Urban control is low compared with territorial size\./g, "El control urbano es bajo comparado con el tamaño territorial."],
  [/No diplomatic action has a strong enough advantage yet\./g, "No hay acción diplomática con suficiente ventaja aún."],
  [/A friendly partner is available for future mutual defense\./g, "Hay un socio amistoso disponible para defensa mutua futura."],
  [/Hostility is high and military readiness is strong enough for border war\./g, "La hostilidad es alta y la preparación militar es suficiente para guerra fronteriza."],
  [/(.+) declared war on (.+)\./g, "$1 declaró la guerra a $2."],
  [/(.+) and (.+) signed a mutual defense alliance\./g, "$1 y $2 firmaron una alianza de defensa mutua."],
  [/(.+) and (.+) agreed to a (\d+)-month truce\./g, "$1 y $2 acordaron una tregua de $3 meses."],
  [/(.+) became a vassal of (.+)\./g, "$1 se convirtió en séquito de $2."],
  [/(.+) submitted to (.+) as a vassal\./g, "$1 se sometió a $2 como séquito."],
  [/(.+) and (.+) dissolved their alliance after relations cooled\./g, "$1 y $2 disolvieron su alianza tras enfriarse las relaciones."],
  [/(.+) from (.+) to (.+) was accepted\./g, "$1 de $2 a $3 fue aceptado."],
  [/(.+) from (.+) to (.+) was created\./g, "$1 de $2 a $3 fue creado."],
  [/(.+) from (.+) to (.+) was expired\./g, "$1 de $2 a $3 expiró."],
  [/(.+) from (.+) to (.+) was rejected\./g, "$1 de $2 a $3 fue rechazado."],
  [/(.+) broke vassalage with (.+)\./g, "$1 rompió su sumisión con $2."],
  [/(.+) rebelled against (.+)\./g, "$1 se rebeló contra su señor $2."],
  [/(.+) dispatched a spy to (.+) for (.+)\./g, "$1 envió un espía a $2 para $3."],
  [/(.+) obtained military and resource intelligence on (.+)\./g, "$1 obtuvo inteligencia militar y de recursos sobre $2."],
  [/(.+) sowed discord between (.+) and (.+)\./g, "$1 sembró discórdia entre $2 y $3."],
  [/(.+) improved relations with (.+) through covert action\./g, "$1 mejoró las relaciones con $2 mediante acción encubierta."],
  [/(.+) damaged relations with (.+) through covert action\./g, "$1 dañó las relaciones con $2 mediante acción encubierta."],
  [/(.+) could not fully pay military upkeep; army morale fell to (\d+)%\./g, "$1 no pudo pagar completamente el mantenimiento militar; la moral del ejército cayó al $2%."],
  [/(.+) lacked military supplies; army morale fell to (\d+)%\./g, "$1 carecía de suministros militares; la moral del ejército cayó al $2%."],
  [/(.+) disbanded (\d+) soldiers to reduce military expenses\./g, "$1 disolvió $2 soldados para reducir gastos militares."],
  [/(\d+) (.+) finished training in (.+)\./g, "$3 completó el entrenamiento de $1 $2."],
  [/(.+) invested surplus resources to develop (.+) to level (\d+)\./g, "$1 invirtió recursos excedentes para desarrollar $2 al nivel $3."],
  [/(.+) redirected an army group toward (.+)\./g, "$1 redirigió un grupo de ejército hacia $2."],
  [/(.+) army group reached (.+)\./g, "El grupo de ejército de $1 llegó a $2."],
  [/(.+) formed an army group for (.+) from (.+) and ordered it toward (.+)\./g, "$1 formó un grupo de ejército para $2 desde $3 y lo ordenó hacia $4."],
  [/(\d+) army groups merged in the same province\./g, "$1 grupos de ejército se fusionaron en la misma provincia."],
  [/(.+) occupied (.+), taking control of its land and resources from (.+)\./g, "$1 ocupó $2, tomando el control de su tierra y recursos de $3."],
  [/(.+) and (.+) ended their war because one side no longer controls territory\./g, "$1 y $2 terminaron su guerra porque un lado ya no controla territorio."],
  [/(.+) and (.+) signed a truce after their armies could no longer reach a viable front\./g, "$1 y $2 firmaron una tregua tras sus ejércitos ya no poder alcanzar un frente viable."],
  [/(.+) lost (.+), its capital city, to (.+)\./g, "$1 perdió $2, su capital, ante $3."],
  [/(.+) lost (.+) to (.+)\./g, "$1 perdió $2 ante $3."],
  [/(.+) lost its cities and population and was defeated by (.+)\./g, "$1 perdió sus ciudades y población y fue derrotado por $2."],
  [/(.+) won the battle for (.+) against (.+)\. Attack (\d+), defense (\d+)\./g, "$1 ganó la batalla por $2 contra $3. Ataque $4, defensa $5."],
  [/(.+) failed the battle for (.+) against (.+)\. Attack (\d+), defense (\d+)\./g, "$1 fracasó en la batalla por $2 contra $3. Ataque $4, defensa $5."],
  [/ Accepted$/g, " Aceptado"], [/ Created$/g, " Creado"], [/ Expired$/g, " Expirado"], [/ Rejected$/g, " Rechazado"],
  [/No active /g, "Sin activo"], [/No /g, "Sin"], [/Unknown /g, "Desconocido"],
];

/** 将界面或模拟文本转换为指定语言；英文是内部规范化源文本。 */
export function localizeText(text: string, language: Language, world?: World) {
  if (language === "en" || !text.trim()) return text;
  const leading = text.match(/^\s*/)?.[0] ?? "";
  const trailing = text.match(/\s*$/)?.[0] ?? "";
  let value = text.trim();
  if (world && language === "zh") {
    const entities = [...world.nations, ...world.cities, ...world.provinces].sort((a, b) => b.nameEn.length - a.nameEn.length);
    for (const entity of entities) value = value.split(entity.nameEn).join(entity.nameZh);
  }
  if (language === "zh") {
    value = staticZh[value] ?? value;
    for (const [pattern, replacement] of phraseZh) value = value.replace(pattern, replacement);
    for (const [english, chinese] of Object.entries(staticZh).sort(([a], [b]) => b.length - a.length)) {
      value = value.split(english).join(chinese);
    }
  } else if (language === "es") {
    value = staticEs[value] ?? value;
    for (const [pattern, replacement] of phraseEs) value = value.replace(pattern, replacement);
    for (const [english, spanish] of Object.entries(staticEs).sort(([a], [b]) => b.length - a.length)) {
      value = value.split(english).join(spanish);
    }
  }
  return `${leading}${value}${trailing}`;
}

/** 返回资源的本地化名称。 */
export function localizeResource(resource: Resource, language: Language) {
  const english = resource.charAt(0).toUpperCase() + resource.slice(1);
  if (language === "zh") return staticZh[english] ?? english;
  if (language === "es") return staticEs[english] ?? english;
  return english;
}

/** 返回地形的本地化名称。 */
export function localizeTerrain(terrain: Terrain, language: Language) {
  const english = terrain.charAt(0).toUpperCase() + terrain.slice(1);
  if (language === "zh") return staticZh[english] ?? english;
  if (language === "es") return staticEs[english] ?? english;
  return english;
}

/** Palabra de unidad en minúsculas para frases ("infantry" → "infantería"). */
export function unitWordL(englishLabel: string, language: Language | EventLang | undefined): string {
  const lower = englishLabel.toLowerCase();
  if (language === "es") return staticEs[lower] ?? lower;
  if (language === "zh") return staticZh[lower] ?? lower;
  return lower;
}
