/** 可本地化的名称条目，用于稳定配置引用与中英文显示。 */
export type LocalizedNameEntry = { id: string; en: string; zh: string; es: string };

/** 国家名称主体池；国家生成时会与政体池随机组合。 */
export const nationNameBases: LocalizedNameEntry[] = [
  { id: "aurora", en: "Aurora", zh: "极光", es: "Aurora" }, { id: "verdant", en: "Verdant", zh: "苍翠", es: "Verde" },
  { id: "sol", en: "Sol", zh: "曜日", es: "Sol" }, { id: "ember", en: "Ember", zh: "余烬", es: "Brasa" },
  { id: "lumen", en: "Lumen", zh: "流明", es: "Lumen" }, { id: "cobalt", en: "Cobalt", zh: "苍蓝", es: "Cobalto" },
  { id: "meridian", en: "Meridian", zh: "子午", es: "Meridiano" }, { id: "horizon", en: "Horizon", zh: "地平", es: "Horizonte" },
  { id: "silver", en: "Silver", zh: "白银", es: "Plata" }, { id: "river", en: "River", zh: "长河", es: "Río" },
  { id: "crown", en: "Crown", zh: "王冠", es: "Corona" }, { id: "aster", en: "Aster", zh: "星芒", es: "Astero" },
];

/** 国家政体池；与名称主体组合形成完整国家名。 */
export const governmentForms: LocalizedNameEntry[] = [
  { id: "republic", en: "Republic", zh: "共和国", es: "República" }, { id: "federation", en: "Federation", zh: "联邦", es: "Federación" },
  { id: "kingdom", en: "Kingdom", zh: "王国", es: "Reino" }, { id: "empire", en: "Empire", zh: "帝国", es: "Imperio" },
  { id: "directorate", en: "Directorate", zh: "统合体", es: "Directorio" }, { id: "commonwealth", en: "Commonwealth", zh: "共同体", es: "Commonwealth" },
  { id: "league", en: "League", zh: "联盟", es: "Liga" }, { id: "assembly", en: "Assembly", zh: "议会国", es: "Asamblea" },
];

/** 省份完整名称池；生成世界时按种子打乱并逐一抽取，确保同一世界内名称不重复。 */
export const provinceNames: LocalizedNameEntry[] = [
  ["northreach", "Northreach", "北境", "nortellegada"], ["southmere", "Southmere", "南湖"],
  ["eastvale", "Eastvale", "东谷", "estevalle"], ["westmarch", "Westmarch", "西疆"],
  ["highplain", "Highplain", "高原", "altollano"], ["lowfen", "Lowfen", "低泽"],
  ["oldwood", "Oldwood", "古林", "viejobosque"], ["newford", "Newford", "新津"],
  ["redridge", "Redridge", "赤岭", "rojocresta"], ["bluebasin", "Bluebasin", "蓝盆地"],
  ["silvercoast", "Silvercoast", "银海岸", "platacosta"], ["goldfield", "Goldfield", "金野"],
  ["greenmoor", "Greenmoor", "翠原", "verdebrezal"], ["blackpass", "Blackpass", "黑隘"],
  ["whiteharbor", "Whiteharbor", "白港", "blancopuerto"], ["clearwater", "Clearwater", "清水"],
  ["brightfall", "Brightfall", "明瀑", "brillantecascada"], ["deepwatch", "Deepwatch", "深望"],
  ["stormgate", "Stormgate", "风暴门", "tormentapuerta"], ["cloudrest", "Cloudrest", "云憩"],
  ["starplain", "Starplain", "星原", "estrellallano"], ["moonvale", "Moonvale", "月谷"],
  ["sunreach", "Sunreach", "日境", "solllegada"], ["stoneford", "Stoneford", "石津"],
  ["ironmarch", "Ironmarch", "铁疆", "hierromarcha"], ["copperhill", "Copperhill", "铜岭"],
  ["jadebasin", "Jadebasin", "玉盆地", "jadecuenca"], ["pearlcoast", "Pearlcoast", "珠岸"],
  ["amberfield", "Amberfield", "琥珀野", "ámbarcampo"], ["crystalmoor", "Crystalmoor", "晶原"],
  ["frostpass", "Frostpass", "霜隘", "escarchapaso"], ["snowharbor", "Snowharbor", "雪港"],
  ["rainwater", "Rainwater", "雨水", "lluviaagua"], ["mistfall", "Mistfall", "雾瀑"],
  ["dawnwatch", "Dawnwatch", "曙望", "amanecervigía"], ["duskgate", "Duskgate", "暮门"],
  ["windrest", "Windrest", "风息", "vientodescanso"], ["thunderplain", "Thunderplain", "雷原"],
  ["riverdale", "Riverdale", "河谷", "ríovalle"], ["lakevale", "Lakevale", "湖谷"],
  ["ashreach", "Ashreach", "灰境", "cenizallegada"], ["pinewood", "Pinewood", "松林"],
  ["oakford", "Oakford", "橡津", "roblevado"], ["wolfmarch", "Wolfmarch", "狼疆"],
  ["falconridge", "Falconridge", "鹰岭", "falconcresta"], ["ravenbasin", "Ravenbasin", "鸦盆地"],
  ["lioncoast", "Lioncoast", "狮岸", "leóncosta"], ["stagfield", "Stagfield", "鹿野"],
  ["foxmoor", "Foxmoor", "狐原", "zorrobrezal"], ["bearpass", "Bearpass", "熊隘"],
  ["eagleharbor", "Eagleharbor", "鹰港", "águilapuerto"], ["willowwater", "Willowwater", "柳水"],
  ["maplefall", "Maplefall", "枫瀑", "maplecascada"], ["cedarwatch", "Cedarwatch", "杉望"],
  ["birchgate", "Birchgate", "桦门", "birchpuerta"], ["elmrest", "Elmrest", "榆憩"],
  ["roseplain", "Roseplain", "蔷薇原", "rosellano"], ["lilyvale", "Lilyvale", "百合谷"],
  ["lotusreach", "Lotusreach", "莲境", "lotusllegada"], ["reedwood", "Reedwood", "芦林"],
  ["sandford", "Sandford", "沙津", "sandvado"], ["saltmarch", "Saltmarch", "盐疆"],
  ["flintridge", "Flintridge", "燧石岭", "flintcresta"], ["claybasin", "Claybasin", "陶土盆地"],
  ["coralcoast", "Coralcoast", "珊瑚岸", "coralcosta"], ["wheatfield", "Wheatfield", "麦野"],
  ["heathermoor", "Heathermoor", "石楠原", "brezobrezal"], ["emberpass", "Emberpass", "余烬隘"],
  ["coalharbor", "Coalharbor", "煤港", "carbónpuerto"], ["springwater", "Springwater", "春水"],
  ["shadowfall", "Shadowfall", "影落", "shadowcascada"], ["crownwatch", "Crownwatch", "王冠望"],
  ["kingsgate", "Kingsgate", "王门", "kingspuerta"], ["queensrest", "Queensrest", "王后憩"],
  ["nobleplain", "Nobleplain", "贵族原", "noblellano"], ["freemenvale", "Freemenvale", "自由民谷"],
  ["templereach", "Templereach", "神殿境", "templollegada"], ["abbeywood", "Abbeywood", "修院林"],
  ["marketford", "Marketford", "市集津", "mercadovado"], ["guildmarch", "Guildmarch", "行会疆"],
  ["auroraridge", "Auroraridge", "极光岭", "auroracresta"], ["meridianbasin", "Meridianbasin", "子午盆地"],
  ["horizoncoast", "Horizoncoast", "地平岸", "horizontecosta"], ["lumenfield", "Lumenfield", "流明野"],
  ["cobaltmoor", "Cobaltmoor", "苍蓝原", "cobaltobrezal"], ["verdantpass", "Verdantpass", "苍翠隘"],
  ["solharbor", "Solharbor", "曜日港", "solpuerto"], ["asterwater", "Asterwater", "星芒水"],
  ["crownfall", "Crownfall", "王冠落", "coronacascada"], ["emberwatch", "Emberwatch", "余烬望"],
  ["rivergate", "Rivergate", "长河门", "ríopuerta"], ["silverrest", "Silverrest", "白银憩"],
  ["goldenplain", "Goldenplain", "黄金原", "doradollano"], ["azurevale", "Azurevale", "天蓝谷"],
  ["crimsonreach", "Crimsonreach", "绯红境", "carmesíllegada"], ["ivorywood", "Ivorywood", "象牙林"],
  ["obsidianford", "Obsidianford", "黑曜津", "obsidianavado"], ["marblemarch", "Marblemarch", "大理石疆"],
  ["graniteridge", "Graniteridge", "花岗岭", "granitocresta"], ["quartzbasin", "Quartzbasin", "石英盆地"],
  ["sapphirecoast", "Sapphirecoast", "蓝宝石岸", "zafirocosta"], ["rubyfield", "Rubyfield", "红宝石野"],
  ["emeraldmoor", "Emeraldmoor", "翡翠原", "esmeraldabrezal"], ["topazpass", "Topazpass", "黄玉隘"],
  ["opalharbor", "Opalharbor", "欧泊港", "ópalopuerto"], ["onyxwater", "Onyxwater", "缟玛瑙水"],
  ["garnetfall", "Garnetfall", "石榴石落", "granatecascada"], ["amethystwatch", "Amethystwatch", "紫晶望"],
  ["diamondgate", "Diamondgate", "钻石门", "diamantepuerta"], ["bronzerest", "Bronzerest", "青铜憩"],
  ["laurelplain", "Laurelplain", "月桂原", "laurelllano"], ["cypressvale", "Cypressvale", "柏谷"],
  ["olivereach", "Olivereach", "橄榄境", "olivollegada"], ["orchardwood", "Orchardwood", "果园林"],
  ["vineyardford", "Vineyardford", "葡萄津", "viñedovado"], ["meadowmarch", "Meadowmarch", "草甸疆"],
  ["highlandridge", "Highlandridge", "高地岭", "tierras altascresta"], ["lowlandbasin", "Lowlandbasin", "低地盆地"],
  ["frontiercoast", "Frontiercoast", "边疆岸", "fronteracosta"], ["heartlandfield", "Heartlandfield", "腹地"],
  ["wildmoor", "Wildmoor", "荒原", "salvajebrezal"], ["farpass", "Farpass", "远隘"],
  ["safeharbor", "Safeharbor", "安港", "seguropuerto"], ["sweetwater", "Sweetwater", "甘泉"],
  ["longfall", "Longfall", "长瀑", "largocascada"], ["farwatch", "Farwatch", "远望"],
  ["irongate", "Irongate", "铁门", "hierropuerta"], ["havenrest", "Havenrest", "安息地"],
  ["grandplain", "Grandplain", "大平原", "granllano"], ["fairvale", "Fairvale", "秀谷"],
].map(([id, en, zh, es]) => ({ id, en, zh, es }));

/** 城市完整名称池；生成时直接抽取，方便策划人员维护。 */
export const cityNames: LocalizedNameEntry[] = [
  ["starhaven", "Starhaven", "星港", "estrellapuerto"], ["rivergate", "Rivergate", "河门"], ["ironford", "Ironford", "铁津"],
  ["brightspire", "Brightspire", "辉塔", "brillantetorre"], ["cloudrest", "Cloudrest", "云栖"], ["emberfall", "Emberfall", "烬落"],
  ["lumenbridge", "Lumenbridge", "光桥", "lumenpuente"], ["cobaltport", "Cobaltport", "苍蓝港"], ["greenwatch", "Greenwatch", "翠望"],
  ["goldenfield", "Goldenfield", "金原", "doradocampo"], ["stonehold", "Stonehold", "石垒"], ["moonmarket", "Moonmarket", "月集"],
  ["sunward", "Sunward", "向阳城", "solguarnición"], ["stormrest", "Stormrest", "息风城"], ["clearwater", "Clearwater", "清泉"],
  ["highgarden", "Highgarden", "高庭", "altojardín"], ["silvercross", "Silvercross", "银渡"], ["newforge", "Newforge", "新炉城"],
  ["redharbor", "Redharbor", "赤港", "Redharbor"], ["northpoint", "Northpoint", "北岬"], ["southvale", "Southvale", "南谷"],
  ["eastmere", "Eastmere", "东湖", "estemar"], ["westcrown", "Westcrown", "西冠"], ["deepwood", "Deepwood", "幽林"],
  ["auricgate", "Auricgate", "鎏金门", "auricpuerta"], ["horizonfall", "Horizonfall", "天际城"], ["meridian", "Meridian", "子午城"],
  ["nova", "Nova", "新星城", "Nova"], ["asterforge", "Asterforge", "星炉"], ["crownrest", "Crownrest", "冠栖"],
  ["verdantford", "Verdantford", "翠津", "verdevado"], ["solhaven", "Solhaven", "曜日港"], ["frostwatch", "Frostwatch", "霜望"],
  ["dawngate", "Dawngate", "曙门", "amanecerpuerta"], ["mistbridge", "Mistbridge", "雾桥"], ["oakheart", "Oakheart", "橡心城"],
  ["sandspire", "Sandspire", "沙塔", "sandtorre"], ["blackfen", "Blackfen", "玄泽"], ["whitecliff", "Whitecliff", "白崖"],
  ["bluegarden", "Bluegarden", "蓝庭", "azuljardín"], ["sunforge", "Sunforge", "日炉"], ["moonford", "Moonford", "月津"],
  ["starbridge", "Starbridge", "星桥", "estrellapuente"], ["rainhaven", "Rainhaven", "雨港"], ["windrest", "Windrest", "风息城"],
  ["pinewatch", "Pinewatch", "松望", "pinovigía"], ["ashmarket", "Ashmarket", "灰集"], ["crystalbay", "Crystal Bay", "晶湾"],
  ["falconreach", "Falconreach", "鹰境", "Falconreach"], ["jadegate", "Jadegate", "玉门"], ["pearlhaven", "Pearlhaven", "珠港"],
  ["thunderford", "Thunderford", "雷津", "rayovado"], ["willowrest", "Willowrest", "柳栖"], ["wolfpoint", "Wolfpoint", "狼岬"],
].map(([id, en, zh, es]) => ({ id, en, zh, es }));
